version: '3.1'
services:
  app-jvm:
    container_name: app-jvm
    image: ivanklp/image-jvm
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jugmadrid-db:5432/jug-madrid
      - SPRING_LIQUIBASE_ENABLED=false
    ports:
      - "8080:8080"
    depends_on:
      - db
  app-native:
    container_name: app-native
    image: ivanklp/image-native
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jugmadrid-db:5432/jug-madrid
      - SPRING_LIQUIBASE_ENABLED=false
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    container_name: jugmadrid-db
    image: postgres:15.1
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jug-madrid
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  sample_db: {}